services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: little_sun
    image: postgres:17.2
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      POSTGRES_PASSWORD: antony15
      DB_NAME: little_sun
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
