export const ROUTE_PATHS = {
  // HOME: "/",
  CREATE_APPOINTMENT: "/create-appointment",
  APPOINTMENTS: "/appointments",
  UPDATE_APPOINTMENT: "/update-appointment",
  CLIENT: "/client",
  NAIL_SERVICE: "/nail-service",
  UDPATE_NAIL_SERVICE: "/update-nail-service",
  CREATE_NAIL_SERVICE: "/create-nail-service",
  CREATE_NAIL_DESIGN: "/nail-nail-design",
  NAIL_DESIGN: "/nail-design",
  UDPATE_NAIL_DESIGN: "/update-nail-design",
  LOGIN: "/",
  REGISTER: "/register",
  FORGOT_PASSWORD: "forgot-password",
  NOT_FOUND: "*",
} as const;
